In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
arr2=np.array([[1,2,3,4,5],[6,7,7,8,6]])
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 7, 8, 6]])

In [11]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7=np.arange(5,20)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Properties and Attributes

In [18]:
## shape, ndim, size,

arr6.itemsize

4

# Indexing and slicing

In [21]:
arr12=np.arange(24).reshape(6,4)

In [22]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
arr12[2]

array([ 8,  9, 10, 11])

In [30]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [31]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [32]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [34]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Operations

In [35]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,7])


In [36]:
arr1+arr2

array([ 5,  7,  9, 11, 12])

In [38]:
arr1>=3

array([False, False,  True,  True,  True])

In [39]:
arr1.max()

5

In [40]:
arr2.max()

7

In [41]:
arr=np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
arr.min(axis=0)#axis==0 for column

array([0, 1, 2, 3])

In [43]:
arr.min(axis=1) # axis==1 for rows

array([ 0,  4,  8, 12, 16, 20])

In [45]:
arr.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [46]:
arr.std()

6.922186552431729

In [47]:
np.median(arr)

11.5

# Reshaping the array

In [51]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
arr.ndim

2

In [54]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])